apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv-temp
spec:
  selector:
    matchLabels:
      app: node
  #replicas: 2 # tells deployment to run 2 pods
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: conv-temp
        image: docker.io/bsspreto/conv-temp:v1
        ports:
        - containerPort: 8080
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi