apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: conv-temp-scaler
spec:
  scaleTargetRef:
    kind: ReplicaSet
    name: conv-temp
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50
