apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv-temp
spec:
  selector:
    matchLabels:
      app: node
  #replicas: 2 # tells deployment to run 2 pods
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: conv-temp
        image: docker.io/bsspreto/conv-temp:v1
        ports:
        - containerPort: 8080
      ---
      apiVersion: apps/v1
      kind: Service
      metadata:
        name: conv-temp-ext
      spec:
        type: LoadBalancer
        selector:
          app: conv-temp
        ports:
          targetPort: 8080
      --- 
      apiVersion: autoscaling/v1
      kind: HorizontalPodAutoscaler
      metadata:
        name: conv-temp-scaler
      spec:
        scaleTargetRef:
          kind: ReplicaSet
          name: conv-temp
         minReplicas: 1
         maxReplicas: 4
         targetCPUUtilizationPercentage: 30
