apiVersion: v1
kind: Deployment
metadata:
  name: conv-temp
spec:
  containers:
    - name: conv-temp
      image: bssouza/conv-temp:v1
      ports:
        - containerPort: 8081
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
