apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
spec:
  selector:
    matchLabels:
      app: node
  replicas: 2 # tells deployment to run 2 pods
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: docker.io/bsspreto/conv-temp
        image: docker.io/bsspreto/conv-temp:v1
        ports:
        - containerPort: 8081
